# Open Liberty JavaEE 7: Docker Sample
#
# This sample demonstrates how to deploy an application to the Open Liberty
# JavaEE 7 docker image.
#

# This sample is based on the JavaEE 7 flavor of the Open Liberty
# docker images:

FROM openliberty/javaee7

# You should put your credentials here, if you plan to push this image
# to a registry

MAINTAINER John Doe

# The application is copied to the deployment folder

COPY sample.war ${DEPLOYMENT_DIR}
