ARG PARENT_IMAGE=icr.io/appcafe/open-liberty:kernel-slim-java8-ibmjava-ubi-micro

# ubi-micro has no package manager; install unzip from ubi-minimal and copy it in
FROM registry.access.redhat.com/ubi10/ubi-minimal AS builder
RUN microdnf -y install unzip && microdnf clean all

FROM $PARENT_IMAGE AS installBundle

ARG VERBOSE=false
ARG LIBERTY_VERSION=26.0.0.9
ARG FEATURES_SHA=971f2f2434b57f39c8329ffc075ed26ba5e23742

# If there is a local copy of the repository use that instead
COPY resources/ /tmp/

# We need unzip when using a local repo; copy it from ubi-minimal builder stage
USER root
COPY --from=builder /usr/bin/unzip /usr/bin/unzip
COPY --from=builder /usr/lib64/libbz2.so* /usr/lib64/
USER 1001

# Install all features
RUN set -eux; \
  if [ ! -f /tmp/openliberty-MavenArtifact-$LIBERTY_VERSION.zip ]; then \
    wget -q https://repo1.maven.org/maven2/io/openliberty/features/features/$LIBERTY_VERSION/features-$LIBERTY_VERSION.json -O /tmp/features-$LIBERTY_VERSION.json; \
    echo "$FEATURES_SHA  /tmp/features-$LIBERTY_VERSION.json" > /tmp/features-$LIBERTY_VERSION.json.sha1; \
    sha1sum -c /tmp/features-$LIBERTY_VERSION.json.sha1; \
  else \
    echo "$FEATURES_SHA  /tmp/openliberty-MavenArtifact-$LIBERTY_VERSION.zip" > /tmp/openliberty-MavenArtifact-$LIBERTY_VERSION.zip.sha1; \
    sha1sum -c /tmp/openliberty-MavenArtifact-$LIBERTY_VERSION.zip.sha1; \
    mkdir /tmp/feature-repo-$LIBERTY_VERSION; \
    unzip -d /tmp/feature-repo-$LIBERTY_VERSION /tmp/openliberty-MavenArtifact-$LIBERTY_VERSION.zip; \
    cp /tmp/feature-repo-$LIBERTY_VERSION/io/openliberty/features/features/$LIBERTY_VERSION/features-$LIBERTY_VERSION.json /tmp; \
    export FEATURE_LOCAL_REPO=/tmp/feature-repo-$LIBERTY_VERSION; \
    export FEATURE_VERIFY=skip; \
  fi; \
  grep \"shortName\" /tmp/features-$LIBERTY_VERSION.json | sed -e 's/.* //' -e 's/,//' | xargs featureUtility installFeature --acceptLicense --noCache; \
  rm -rf /output/workarea /output/logs; \
  find /opt/ol/wlp ! -perm -g=rw -print0 | xargs -r -0 chmod g+rw;

ARG PARENT_IMAGE=icr.io/appcafe/open-liberty:kernel-slim-java8-ibmjava-ubi-micro
FROM $PARENT_IMAGE
ARG VERBOSE=false

# Copy the runtime
COPY --from=installBundle --chown=1001:0 /opt/ol/wlp /opt/ol/wlp

COPY --chown=1001:0 server-http-port-enabled.xml /config/server.xml

# Create a new SCC layer
RUN if [ "$OPENJ9_SCC" = "true" ]; then populate_scc.sh; fi \
    && rm -rf /output/messaging /output/resources/security /logs/* $WLP_OUTPUT_DIR/.classCache \
    && find /opt/ol/wlp/output ! -perm -g=rwx -print0 | xargs -0 -r chmod g+rwx
