#!/bin/bash

keystorePath="/config/configDropins/defaults/keystore.xml"

if [[ "$KEYSTORE_REQUIRED" == "true" ]]
then
  if [ ! -e $keystorePath ]
  then
    # Generate the keystore.xml
    PASSWORD=$(openssl rand -base64 32)
    XML="<server description=\"Default Server\"><keyStore id=\"defaultKeyStore\" password=\"$PASSWORD\" /></server>"

    # Create the keystore.xml file and place in configDropins
    mkdir -p $(dirname $keystorePath)
    echo $XML > $keystorePath
  fi
fi

# Pass on to the real server run
exec /opt/ibm/wlp/bin/server $@
