#!/bin/sh

set -e

keystorePath="/config/configDropins/defaults/keystore.xml"

if [ "$KEYSTORE_REQUIRED" = "true" ]
then
  if [ "$1" = "server" ] || [ "$1" = "/opt/ol/wlp/bin/server" ]
  then
    if [ ! -e $keystorePath ]
    then
      # Generate the keystore.xml
      export keystore_password=$(openssl rand -base64 32)
    fi
  fi
fi

# Pass on to the real server run
exec "$@"
